set(SUPPORTS_CXX "FALSE")
if("${COMPILER}" STREQUAL "intel")
  set(MPIFC "mpif90")
  set(FFLAGS_NOOPT "-O0")
  set(CXXFLAGS "-std=c++11 -fp-model source")
  set(MPICC "mpicc")
  set(SCC "icc")
  set(MPICXX "mpicxx")
  set(HAS_F2008_CONTIGUOUS "TRUE")
  set(CXX_LDFLAGS "-cxxlib")
  set(SUPPORTS_CXX "TRUE")
  set(FFLAGS "-convert big_endian -assume byterecl -ftz -traceback -assume realloc_lhs -fp-model source")
  set(FIXEDFLAGS "-fixed -132")
  set(CXX_LINKER "FORTRAN")
  set(FC_AUTO_R8 "-r8")
  set(CFLAGS "-O2 -fp-model precise -std=gnu99")
  set(FREEFLAGS "-free")
  set(SFC "ifort")
  set(SCXX "icpc")
endif()
if("${COMPILER}" STREQUAL "pgi")
  set(MPIFC "mpif90")
  set(FFLAGS_NOOPT "-O0")
  set(MPICC "mpicc")
  set(SCC "pgcc")
  set(LDFLAGS "-time -Wl,--allow-multiple-definition")
  set(MPICXX "mpicxx")
  set(HAS_F2008_CONTIGUOUS "FALSE")
  set(FFLAGS "-i4 -time -Mstack_arrays  -Mextend -byteswapio -Mflushz -Kieee -Mallocatable=03")
  set(FIXEDFLAGS "-Mfixed")
  set(FC_AUTO_R8 "-r8")
  set(CFLAGS "-time")
  set(FREEFLAGS "-Mfree")
  set(SFC "pgf95")
  set(SCXX "pgc++")
endif()
if("${COMPILER}" STREQUAL "intel")
  set(PIO_FILESYSTEM_HINTS "lustre")
  set(PNETCDF_PATH "$ENV{PNETCDF_HOME}")
  set(NETCDF_PATH "$ENV{NETCDF_HOME}")
  set(CONFIG_ARGS "--host=Linux")
  if("${MPILIB}" STREQUAL "impi")
    set(MPIFC "mpiifort")
    set(MPICC "mpiicc")
    set(MPICXX "mpiicpc")
  endif()
endif()
if("${COMPILER}" STREQUAL "pgi")
  set(PIO_FILESYSTEM_HINTS "lustre")
  set(PNETCDF_PATH "$ENV{PNETCDF_HOME}")
  set(CXX_LIBS "-lstdc++")
  set(NETCDF_PATH "$ENV{NETCDF_HOME}")
  set(SUPPORTS_CXX "TRUE")
  set(CONFIG_ARGS "--host=Linux")
  set(CXX_LINKER "FORTRAN")
  if("${MPILIB}" STREQUAL "impi")
    set(MPIFC "mpipgf90")
    set(MPICC "mpipgcc")
    set(MPICXX "mpipgcxx")
  endif()
endif()
if("${COMPILER}" STREQUAL "intel")
  set(CPPDEFS "${CPPDEFS}  -DFORTRANUNDERSCORE -DNO_R16 -DCPRINTEL")
  set(CPPDEFS "${CPPDEFS}  -DLINUX")
  if("${compile_threaded}" STREQUAL "TRUE")
    set(CFLAGS "${CFLAGS}  -qopenmp")
  endif()
  if("${DEBUG}" STREQUAL "FALSE")
    set(CFLAGS "${CFLAGS}  -O2 -debug minimal")
    set(CFLAGS "${CFLAGS}  -O2")
  endif()
  if("${DEBUG}" STREQUAL "TRUE")
    set(CFLAGS "${CFLAGS}  -O0 -g")
  endif()
  if("${COMP_NAME}" STREQUAL "gptl")
    set(CFLAGS "${CFLAGS}  -DHAVE_SLASHPROC")
  endif()
  if("${compile_threaded}" STREQUAL "TRUE")
    set(CXXFLAGS "${CXXFLAGS}  -qopenmp")
    set(FFLAGS "${FFLAGS}  -qopenmp")
  endif()
  if("${DEBUG}" STREQUAL "TRUE")
    set(CXXFLAGS "${CXXFLAGS}  -O0 -g")
    set(FFLAGS "${FFLAGS}  -O0 -g -check uninit -check bounds -check pointers -fpe0 -check noarg_temp_created")
    set(FFLAGS "${FFLAGS}  -g -traceback  -O0 -fpe0 -check  all -check noarg_temp_created -ftrapuv -init=snan")
  endif()
  if("${DEBUG}" STREQUAL "FALSE")
    set(CXXFLAGS "${CXXFLAGS}  -O2")
    set(FFLAGS "${FFLAGS}  -O2 -debug minimal")
    set(FFLAGS "${FFLAGS}  -O2")
  endif()
  if("${compile_threaded}" STREQUAL "TRUE")
    set(LDFLAGS "${LDFLAGS}  -qopenmp")
  endif()
endif()
if("${COMPILER}" STREQUAL "pgi")
  set(CPPDEFS "${CPPDEFS}  -DFORTRANUNDERSCORE -DNO_SHR_VMATH -DNO_R16 -DCPRPGI")
  set(CPPDEFS "${CPPDEFS}  -DLINUX")
  if("${compile_threaded}" STREQUAL "TRUE")
    set(FFLAGS "${FFLAGS}  -mp")
    set(CFLAGS "${CFLAGS}  -mp")
  endif()
  if("${DEBUG}" STREQUAL "TRUE")
    set(FFLAGS "${FFLAGS}  -O0 -g -Ktrap=fp -Mbounds -Kieee")
    set(FFLAGS "${FFLAGS} -C -Mbounds -traceback -Mchkfpstk -Mchkstk -Mdalign  -Mdepchk  -Mextend -Miomutex -Mrecursive  -Ktrap=fp -O0 -g -byteswapio -Meh_frame")
  endif()
  if("${DEBUG}" STREQUAL "FALSE")
    set(FFLAGS "${FFLAGS}  -O2")
    set(CFLAGS "${CFLAGS}  -O2")
  endif()
  if("${COMP_NAME}" STREQUAL "dwav")
    set(FFLAGS "${FFLAGS}  -Mnovect")
  endif()
  if("${COMP_NAME}" STREQUAL "dice")
    set(FFLAGS "${FFLAGS}  -Mnovect")
  endif()
  if("${COMP_NAME}" STREQUAL "dlnd")
    set(FFLAGS "${FFLAGS}  -Mnovect")
  endif()
  if("${COMP_NAME}" STREQUAL "datm")
    set(FFLAGS "${FFLAGS}  -Mnovect")
  endif()
  if("${COMP_NAME}" STREQUAL "docn")
    set(FFLAGS "${FFLAGS}  -Mnovect")
  endif()
  if("${COMP_NAME}" STREQUAL "cam")
    set(FFLAGS "${FFLAGS} -Mnovect")
  endif()
  if("${COMP_NAME}" STREQUAL "gptl")
    set(CFLAGS "${CFLAGS}  -DHAVE_SLASHPROC")
  endif()
  if("${COMP_NAME}" STREQUAL "drof")
    set(FFLAGS "${FFLAGS}  -Mnovect")
  endif()
  if("${compile_threaded}" STREQUAL "TRUE")
    set(LDFLAGS "${LDFLAGS}  -mp")
  endif()
endif()
if("${COMPILER}" STREQUAL "intel")
  set(SLIBS "-lpmi -L${NETCDF_PATH}/lib -lnetcdf -lnetcdff -L$ENV{MKL_PATH}/lib/intel64/ -lmkl_rt $ENV{PNETCDF_LIBRARIES}")
endif()
if("${COMPILER}" STREQUAL "pgi")
  set(SLIBS "${SLIBS}  -lpmi -L${NETCDF_PATH}/lib -lnetcdf -lnetcdff -L$ENV{MKL_PATH}/lib/intel64/ -lmkl_rt $ENV{PNETCDF_LIBRARIES}")
endif()
